#!/bin/bash
# this file is intended to be used with qsub, for job submition
#
#PBS -S /bin/bash
#PBS -N HBT.$run
# usually HBT consumes 2~3 times the memory size to hold Pdat(Pos,Vel,ID)?
# to be safe, 5 times this much memory would be enough
##PBS -l mem=10gb
#PBS -l nodes=1:ppn=12
#PBS -j oe

cd $PBS_O_WORKDIR

ulimit -s unlimited

#~ source /etc/profile.d/modules.csh

export HBT_VERSION=8.7
export OMP_SCHEDULE=dynamic
export OMP_DYNAMIC=FALSE # this works for icc v11.1.072, 
# but seems not always use the maximum available number of cpus allowed by NUM_THREADS
# so better not allow it to adjust. shit.
export KMP_BLOCKTIME=0  # this seems to help a lot, to reuse thread immediately after its job is finished
export OMP_NUM_THREADS=24
export OMP_NESTED=0
export RUN_NUM=$run

cp $PBS_NODEFILE nodefile
date 
echo "BT.$RUN_NUM started using schedule $OMP_SCHEDULE and omp_dynamic state is $OMP_DYNAMIC" 
echo "with $OMP_NUM_THREADS threads" 

./HBT.$RUN_NUM $snapstart $snapend

