#!/bin/bash
export HBT_VERSION=8.7c
export OMP_SCHEDULE=dynamic
export OMP_DYNAMIC=FALSE # this works for icc v11.1.072, 
# but seems not always use the maximum available number of cpus allowed by NUM_THREADS
# so better not allow it to adjust. 
export KMP_BLOCKTIME=0  # this seems to help a lot, to reuse thread immediately after its job is finished
export OMP_NUM_THREADS=512
export OMP_NESTED=0
export RUN_NUM=6620

echo " " >>nohup.$RUN_NUM
date >>nohup.$RUN_NUM
echo "HBT.$RUN_NUM started using schedule $OMP_SCHEDULE and omp_dynamic state is $OMP_DYNAMIC" >>nohup.$RUN_NUM
echo "with $OMP_NUM_THREADS threads" >>nohup.$RUN_NUM

# ulimit -u unlimited #user process
ulimit -m unlimited #memory
# ulimit -n unlimited #openfiles
ulimit -s unlimited #stack
ulimit -v unlimited #virtual

#nohup ./HBT.$RUN_NUM "$@" 1>>nohup.$RUN_NUM 2>&1 &
for snap in {77..99}
do
date;free -g |mail -s "snapshot $snap started" hanjiaxin@gmail.com -- -f HBT@uv2000
/usr/bin/time -v ./HBT.$RUN_NUM $snap >time.$RUN_NUM.$snap 2>&1
date;free -g; cat time.$RUN_NUM.$snap |mail -s "snapshot $snap finished" hanjiaxin@gmail.com -- -f HBT@uv2000
done