#!/bin/bash
export HBT_VERSION=8.7c
export OMP_SCHEDULE=dynamic
export OMP_DYNAMIC=FALSE # this works for icc v11.1.072, 
# but seems not always use the maximum available number of cpus allowed by NUM_THREADS
# so better not allow it to adjust. shit.
export KMP_BLOCKTIME=0  # this seems to help a lot, to reuse thread immediately after its job is finished
export OMP_NUM_THREADS=64
export OMP_NESTED=0
export RUN_NUM=6702

echo " " >>nohup.$RUN_NUM
date >>nohup.$RUN_NUM
echo "HBT.$RUN_NUM started using schedule $OMP_SCHEDULE and omp_dynamic state is $OMP_DYNAMIC" >>nohup.$RUN_NUM
echo "with $OMP_NUM_THREADS threads" >>nohup.$RUN_NUM

nohup ./HBT.$RUN_NUM "$@" 1>>nohup.$RUN_NUM 2>&1 &
