function plot_Mstart_stat(countM,mbin,countKt,kbin)
y=countM(:,1);y0=countM(:,2);y6=countM(:,3);y1=countM(:,4);yc=countM(:,5);yv=countM(:,6);
x=mbin;
figure;subplot(1,2,1);
stairs(x,y/sum(y),'r-');
hold on;
stairs(x,y0/sum(y0),'k-.');
stairs(x,y1/sum(y1),'k:');
stairs(x,y6/sum(y6),'b--');
stairs(x,yc/sum(yc),'g');
stairs(x,yv/sum(yv),'c');
legend('D=5/4*(2+\kappa_t)^{1/3}Rvir','D=2^{1/3}Rvir','D=3^{1/3}Rvir','D=1.8*Rvir','D=1.5*3^{1/3}Rvir','D=Rvir');
% legend('D=(2+\kappa_t)^{1/3}Rvir','D=2^{1/3}Rvir','D=3^{1/3}Rvir','D=1.8*Rvir','D=1.5*3^{1/3}Rvir','D=Rvir');
xlabel('Mtidal/Mmax');ylabel('Fraction(=Mtidal/Mmax)');
hold off;
y=cumsum(y(end:-1:1));y=y(end:-1:1);
y0=cumsum(y0(end:-1:1));y0=y0(end:-1:1);
y6=cumsum(y6(end:-1:1));y6=y6(end:-1:1);
y1=cumsum(y1(end:-1:1));y1=y1(end:-1:1);
yc=cumsum(yc(end:-1:1));yc=yc(end:-1:1);
yv=cumsum(yv(end:-1:1));yv=yv(end:-1:1);
subplot(1,2,2);stairs(x,y./y(1),'r-');
hold on;
stairs(x,y0./y0(1),'k-.');
stairs(x,y1./y1(1),'k:');
stairs(x,y6./y6(1),'b--');
stairs(x,yc./yc(1),'g');
stairs(x,yv./yv(1),'c');
legend('D=5/4*(2+\kappa_t)^{1/3}Rvir','D=2^{1/3}Rvir','D=3^{1/3}Rvir','D=1.8*Rvir','D=1.5*3^{1/3}Rvir','D=Rvir');
% legend('D=(2+\kappa_t)^{1/3}Rvir','D=2^{1/3}Rvir','D=3^{1/3}Rvir','D=1.8*Rvir','D=1.5*3^{1/3}Rvir','D=Rvir');
xlabel('Mtidal/Mmax');ylabel('Fraction(>Mtidal/Mmax)');%title('m/M~[0.01,0.1]');
hold off;
ykt=countKt;
figure;loglog(kbin,ykt,'o --');xlabel('K_t');ylabel('N');
ykt=ykt(1:end-1)'./diff(kbin);
figure;loglog(kbin(1:end-1),ykt,'. -');xlabel('K_t');ylabel('dN/dK_t');